<?php

return [
    'number_of_reserved_item' => 10,
    // ログファイル出力先
    'logs' => [
        'application_log' => '/logs/application/application.log',
        'access_log'      => '/logs/access/access.log',
        'query_log' => [
            'query_log'         => '/logs/query/query.log',
            'exception_pattern' => ['select', 'insert']
        ]
    ],
    'data_link' => [
        'global' => [
            // 自動連携 エラーメール送信先
            'error_mail_to' => [
                ['name' => '宛先１', 'email' => 'vvp@pci-xxxx.jp'],
                ['name' => '宛先２', 'email' => 'sol@pci-xxxx.jp'],
                ['name' => '宛先３', 'email' => 'aios@pci-xxxx.jp']
            ],
            // 自動連携 Zipファイル保存期間
            'storage_period'           => "1 month"
        ],
        'master' => [
            // エンドユーザマスタ自動連携 設定値
            'end_users' => [
                'program_name'     => "エンドユーザマスタ自動連携",
                'end_file_path'    => "/mnt/scp_sv/master/BS36BF02.end",
                'tsv_file_path'    => "/mnt/scp_sv/master/BS36BF02.txt",
                'zip_file_path'    => "/home/backup/base_plus/",
                'zip_file_name'    => "%s_end_users.zip",
                'tsv_file_columns' => 90,
                'set_column_index' => [
                    'end_user_code'                => ['index' => 1,'validate' => 'required|string|max:8'],
                    'application_started_on'       => ['index' => 2,'validate' => 'required|date|max:8'],
                    'end_user_name'                => ['index' => 4,'validate' => 'nullable|string|max:50'],
                    'end_user_name2'               => ['index' => 5,'validate' => 'nullable|string|max:50'],
                    'end_user_abbreviation'        => ['index' => 6,'validate' => 'nullable|string|max:20'],
                    'end_user_name_kana'           => ['index' => 7,'validate' => 'nullable|string|max:30'],
                    'end_user_name_english'        => ['index' => 8,'validate' => 'nullable|string|max:65'],
                    'end_user_staff_name'          => ['index' => 9,'validate' => 'nullable|string|max:30'],
                    'mail_address'                 => ['index' => 10,'validate' => 'nullable|string|max:30'],
                    'currency_code'                => ['index' => 11,'validate' => 'nullable|string|max:3'],
                    'delivery_destination_code'    => ['index' => 12,'validate' => 'nullable|string|max:10'],
                    'seller_code'                  => ['index' => 13,'validate' => 'nullable|string|max:8'],
                    'seller_name'                  => ['index' => 14,'validate' => 'nullable|string|max:30'],
                    'pickup_slip_message'          => ['index' => 15,'validate' => 'nullable|string|max:40'],
                    'statement_of_delivery_class'      => ['index' => 16,'validate' => 'nullable|numeric|in:0,1,2,3,4,5'],
                    'statement_of_delivery_price_show_class' => ['index' => 17,'validate' => 'nullable|numeric|in:1,2,3,4'],
                    'abroad_shipment_price_show_class' => ['index' => 18,'validate' => 'nullable|numeric|in:1,2'],
                    'export_managing_class'        => ['index' => 19,'validate' => 'nullable|numeric|in:1,2'],
                    'export_exchange_rate_code'    => ['index' => 20,'validate' => 'nullable|numeric|in:01,02,03,04,05'],
                    'remarks1'                     => ['index' => 21,'validate' => 'nullable|string|max:50'],
                    'remarks2'                     => ['index' => 22,'validate' => 'nullable|string|max:50'],
                    'remarks3'                     => ['index' => 23,'validate' => 'nullable|string|max:50'],
                    'remarks4'                     => ['index' => 24,'validate' => 'nullable|string|max:50'],
                    'remarks5'                     => ['index' => 25,'validate' => 'nullable|string|max:50'],
                    'remarks6'                     => ['index' => 26,'validate' => 'nullable|string|max:50'],
                    'loading_port_code'            => ['index' => 27,'validate' => 'nullable|string|max:4'],
                    'loading_port_name'            => ['index' => 28,'validate' => 'nullable|string|max:30'],
                    'drop_port_code'               => ['index' => 29,'validate' => 'nullable|string|max:4'],
                    'drop_port_name'               => ['index' => 30,'validate' => 'nullable|string|max:30'],
                    'exchange_rate_port_code'      => ['index' => 31,'validate' => 'nullable|string|max:4'],
                    'exchange_rate_port_name'      => ['index' => 32,'validate' => 'nullable|string|max:30'],
                    'lot_managing_target_flag'     => ['index' => 33,'validate' => 'nullable|boolean'],
                    'end_user_remark'              => ['index' => 34,'validate' => 'nullable|string|max:50'],
                    'end_user_request_number'      => ['index' => 35,'validate' => 'nullable|string|max:5'],
                    'statement_of_delivery_remark_class'       => ['index' => 36,'validate' => 'nullable|numeric|in:1,2,3,4'],
                    'statement_of_delivery_buyer_remark_class' => ['index' => 37,'validate' => 'nullable|numeric|in:1,2'],
                    'postal_code'                  => ['index' => 38,'validate' => 'nullable|string|max:10'],
                    'address'                      => ['index' => 39,'validate' => 'nullable|string|max:50'],
                    'address2'                     => ['index' => 40,'validate' => 'nullable|string|max:50'],
                    'address3'                     => ['index' => 41,'validate' => 'nullable|string|max:50'],
                    'abroad_address'               => ['index' => 42,'validate' => 'nullable|string|max:50'],
                    'abroad_address2'              => ['index' => 43,'validate' => 'nullable|string|max:50'],
                    'abroad_address3'              => ['index' => 44,'validate' => 'nullable|string|max:50'],
                    'phone_number'                 => ['index' => 45,'validate' => 'nullable|string|max:20'],
                    'country_code'                 => ['index' => 46,'validate' => 'nullable|string|max:2'],
                    'prefecture_code'              => ['index' => 47,'validate' => 'nullable|string|max:3'],
                    'export_target_flag'           => ['index' => 48,'validate' => 'nullable|boolean'],
                    'group_company_flag'           => ['index' => 49,'validate' => 'nullable|boolean'],
                    'company_code'                 => ['index' => 50,'validate' => 'nullable|string|max:6'],
                    'company_name'                 => ['index' => 51,'validate' => 'nullable|string|max:50'],
                    'company_abbreviation'         => ['index' => 52,'validate' => 'nullable|string|max:20'],
                    'company_name_kana'            => ['index' => 53,'validate' => 'nullable|string|max:30'],
                    'company_name_english'         => ['index' => 54,'validate' => 'nullable|string|max:50'],
                    'company_group_code'           => ['index' => 55,'validate' => 'nullable|string|max:8'],
                    'company_group_name'           => ['index' => 56,'validate' => 'nullable|string|max:40'],
                    'company_group_name_english'   => ['index' => 57,'validate' => 'nullable|string|max:50'],
                    'reserved_text1'               => ['index' => 58,'validate' => 'nullable|string|max:200'],
                    'reserved_text2'               => ['index' => 59,'validate' => 'nullable|string|max:200'],
                    'reserved_text3'               => ['index' => 60,'validate' => 'nullable|string|max:200'],
                    'reserved_text4'               => ['index' => 61,'validate' => 'nullable|string|max:200'],
                    'reserved_text5'               => ['index' => 62,'validate' => 'nullable|string|max:200'],
                    'reserved_text6'               => ['index' => 63,'validate' => 'nullable|string|max:200'],
                    'reserved_text7'               => ['index' => 64,'validate' => 'nullable|string|max:200'],
                    'reserved_text8'               => ['index' => 65,'validate' => 'nullable|string|max:200'],
                    'reserved_text9'               => ['index' => 66,'validate' => 'nullable|string|max:200'],
                    'reserved_text10'              => ['index' => 67,'validate' => 'nullable|string|max:200'],
                    'reserved_number1'             => ['index' => 68,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number2'             => ['index' => 69,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number3'             => ['index' => 70,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number4'             => ['index' => 71,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number5'             => ['index' => 72,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number6'             => ['index' => 73,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number7'             => ['index' => 74,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number8'             => ['index' => 75,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number9'             => ['index' => 76,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number10'            => ['index' => 77,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'base_plus_delete_flag'        => ['index' => 78,'validate' => 'nullable|boolean'],
                    'base_plus_created_at'         => ['index' => 81,'validate' => 'nullable|date'],
                    'base_plus_user_created_by'    => ['index' => 82,'validate' => 'nullable|string|max:8'],
                    'base_plus_program_created_by' => ['index' => 83,'validate' => 'nullable|string|max:12'],
                    'base_plus_updated_at'         => ['index' => 86,'validate' => 'nullable|date'],
                    'base_plus_user_updated_by'    => ['index' => 87,'validate' => 'nullable|string|max:8'],
                    'base_plus_program_updated_by' => ['index' => 88,'validate' => 'nullable|string|max:12']
                ],
                'set_fix_info' => [
                    'creating_type' => 1,
                    'can_display'   => true
                ]
            ],
            // 納入先マスタ自動連携 設定値
            'delivery_destinations' => [
                'program_name'     => "納入先マスタ自動連携処理",
                'end_file_path'    => "/mnt/scp_sv/master/BS36BF03.end",
                'tsv_file_path'    => "/mnt/scp_sv/master/BS36BF03.txt",
                'zip_file_path'    => "/home/backup/base_plus/",
                'zip_file_name'    => "%s_delivery_destinations.zip",
                'tsv_file_columns' => 60,
                'set_column_index' => [
                    'delivery_destination_code'          => ['index' => 1, 'validate' => 'required|string|max:10'],
                    'delivery_destination_name'          => ['index' => 2, 'validate' => 'nullable|string|max:50'],
                    'delivery_destination_name2'         => ['index' => 3, 'validate' => 'nullable|string|max:50'],
                    'delivery_destination_abbreviation'  => ['index' => 4, 'validate' => 'nullable|string|max:20'],
                    'delivery_destination_name_kana'     => ['index' => 5, 'validate' => 'nullable|string|max:30'],
                    'delivery_destination_name_english'  => ['index' => 6, 'validate' => 'nullable|string|max:65'],
                    'postal_code'                        => ['index' => 7, 'validate' => 'nullable|string|max:10'],
                    'address'                            => ['index' => 8, 'validate' => 'nullable|string|max:50'],
                    'address2'                           => ['index' => 9, 'validate' => 'nullable|string|max:50'],
                    'address3'                           => ['index' => 10,'validate' => 'nullable|string|max:50'],
                    'abroad_address'                     => ['index' => 11,'validate' => 'nullable|string|max:50'],
                    'abroad_address2'                    => ['index' => 12,'validate' => 'nullable|string|max:50'],
                    'abroad_address3'                    => ['index' => 13,'validate' => 'nullable|string|max:50'],
                    'phone_number'                       => ['index' => 14,'validate' => 'nullable|string|max:20'],
                    'extension_number'                   => ['index' => 15,'validate' => 'nullable|string|max:15'],
                    'fax_number'                         => ['index' => 16,'validate' => 'nullable|string|max:15'],
                    'staff_abbreviation'                 => ['index' => 17,'validate' => 'nullable|string|max:10'],
                    'mail_address'                       => ['index' => 18,'validate' => 'nullable|string|max:30'],
                    'statement_of_delivery_message'      => ['index' => 19,'validate' => 'nullable|string|max:40'],
                    'statement_of_delivery_output_class' => ['index' => 20,'validate' => 'nullable|numeric|in:0,1,2,3,4'],
                    'shipping_label_unnecessary_flag'    => ['index' => 21,'validate' => 'nullable|boolean'],
                    'export_target_flag'                 => ['index' => 22,'validate' => 'nullable|boolean'],
                    'country_code'                       => ['index' => 23,'validate' => 'nullable|string|max:2'],
                    'prefecture_code'                    => ['index' => 24,'validate' => 'nullable|string|max:3'],
                    'shipment_way_class'                 => ['index' => 25,'validate' => 'nullable|numeric|in:3,5,6,8,9'],
                    'delivery_destination_class'         => ['index' => 26,'validate' => 'nullable|numeric|in:1,2,3,4'],
                    'cii_company_code'                   => ['index' => 27,'validate' => 'nullable|string|max:12'],
                    'reserved_text1'                     => ['index' => 28,'validate' => 'nullable|string|max:200'],
                    'reserved_text2'                     => ['index' => 29,'validate' => 'nullable|string|max:200'],
                    'reserved_text3'                     => ['index' => 30,'validate' => 'nullable|string|max:200'],
                    'reserved_text4'                     => ['index' => 31,'validate' => 'nullable|string|max:200'],
                    'reserved_text5'                     => ['index' => 32,'validate' => 'nullable|string|max:200'],
                    'reserved_text6'                     => ['index' => 33,'validate' => 'nullable|string|max:200'],
                    'reserved_text7'                     => ['index' => 34,'validate' => 'nullable|string|max:200'],
                    'reserved_text8'                     => ['index' => 35,'validate' => 'nullable|string|max:200'],
                    'reserved_text9'                     => ['index' => 36,'validate' => 'nullable|string|max:200'],
                    'reserved_text10'                    => ['index' => 37,'validate' => 'nullable|string|max:200'],
                    'reserved_number1'                   => ['index' => 38,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number2'                   => ['index' => 39,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number3'                   => ['index' => 40,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number4'                   => ['index' => 41,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number5'                   => ['index' => 42,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number6'                   => ['index' => 43,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number7'                   => ['index' => 44,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number8'                   => ['index' => 45,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number9'                   => ['index' => 46,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'reserved_number10'                  => ['index' => 47,'validate' => 'nullable|numeric|max:999999999999999999.9'],
                    'base_plus_delete_flag'              => ['index' => 48,'validate' => 'nullable|boolean'],
                    'base_plus_created_at'               => ['index' => 51,'validate' => 'nullable|date'],
                    'base_plus_user_created_by'          => ['index' => 52,'validate' => 'nullable|string|max:8'],
                    'base_plus_program_created_by'       => ['index' => 53,'validate' => 'nullable|string|max:12'],
                    'base_plus_updated_at'               => ['index' => 56,'validate' => 'nullable|date'],
                    'base_plus_user_updated_by'          => ['index' => 57,'validate' => 'nullable|string|max:8'],
                    'base_plus_program_updated_by'       => ['index' => 58,'validate' => 'nullable|string|max:12']
                ],
                'set_fix_info' => [
                    'creating_type' => 1,
                    'can_display'   => true
                ]
            ],
            'suppliers' => [
                'program_name'     => "仕入先マスタ自動連携処理",
                'end_file_path'    => "/mnt/scp_sv/master/BS36BF04.end",
                'tsv_file_path'    => "/mnt/scp_sv/master/BS36BF04.txt",
                'zip_file_path'    => "/home/backup/base_plus/",
                'zip_file_name'    => "%s_suppliers.zip",
                'tsv_file_columns' => 65,
                'set_column_index' => [
                    'supplier_code'                 => ['index' => 1, 'validate' => 'bail|required|string|max:8'],
                    'application_started_on'        => ['index' => 2, 'validate' => 'bail|required|string|max:8'],
                    'supplier_name'                 => ['index' => 4, 'validate' => 'bail|required|string|max:50'],
                    'supplier_name2'                => ['index' => 5, 'validate' => 'bail|nullable|string|max:50'],
                    'supplier_abbreviation'         => ['index' => 6, 'validate' => 'bail|nullable|string|max:20'],
                    'supplier_name_kana'            => ['index' => 7, 'validate' => 'bail|nullable|string|max:30'],
                    'supplier_name_english'         => ['index' => 8, 'validate' => 'bail|nullable|string|max:65'],
                    'supplier_staff_name'           => ['index' => 9, 'validate' => 'bail|nullable|string|max:30'],
                    'mail_address'                  => ['index' => 10, 'validate' => 'bail|nullable|string|max:30'],
                    'currency_code'                 => ['index' => 11, 'validate' => 'bail|nullable|string|max:3'],
                    'supplier_class'                => ['index' => 12, 'validate' => 'bail|nullable|string|max:1'],
                    'postal_code'                   => ['index' => 13, 'validate' => 'bail|nullable|string|max:10'],
                    'address'                       => ['index' => 14, 'validate' => 'bail|nullable|string|max:50'],
                    'address2'                      => ['index' => 15, 'validate' => 'bail|nullable|string|max:50'],
                    'address3'                      => ['index' => 16, 'validate' => 'bail|nullable|string|max:50'],
                    'abroad_address'                => ['index' => 17, 'validate' => 'bail|nullable|string|max:50'],
                    'abroad_address2'               => ['index' => 18, 'validate' => 'bail|nullable|string|max:50'],
                    'abroad_address3'               => ['index' => 19, 'validate' => 'bail|nullable|string|max:50'],
                    'phone_number'                  => ['index' => 20, 'validate' => 'bail|nullable|string|max:20'],
                    'country_code'                  => ['index' => 21, 'validate' => 'bail|nullable|string|max:2'],
                    'prefecture_code'               => ['index' => 22, 'validate' => 'bail|nullable|string|max:3'],
                    'export_target_flag'            => ['index' => 23, 'validate' => 'bail|nullable|boolean|max:1'],
                    'group_company_flag'            => ['index' => 24, 'validate' => 'bail|nullable|boolean|max:1'],
                    'company_code'                  => ['index' => 25, 'validate' => 'bail|nullable|string|max:6'],
                    'company_name'                  => ['index' => 26, 'validate' => 'bail|nullable|string|max:50'],
                    'company_abbreviation'          => ['index' => 27, 'validate' => 'bail|nullable|string|max:20'],
                    'company_name_kana'             => ['index' => 28, 'validate' => 'bail|nullable|string|max:30'],
                    'company_name_english'          => ['index' => 29, 'validate' => 'bail|nullable|string|max:50'],
                    'company_group_code'            => ['index' => 30, 'validate' => 'bail|nullable|string|max:8'],
                    'company_group_name'            => ['index' => 31, 'validate' => 'bail|nullable|string|max:40'],
                    'company_group_name_english'    => ['index' => 32, 'validate' => 'bail|nullable|string|max:50'],
                    'reserved_text1'                => ['index' => 33, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text2'                => ['index' => 34, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text3'                => ['index' => 35, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text4'                => ['index' => 36, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text5'                => ['index' => 37, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text6'                => ['index' => 38, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text7'                => ['index' => 39, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text8'                => ['index' => 40, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text9'                => ['index' => 41, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text10'               => ['index' => 42, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_number1'              => ['index' => 43, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number2'              => ['index' => 44, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number3'              => ['index' => 45, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number4'              => ['index' => 46, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number5'              => ['index' => 47, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number6'              => ['index' => 48, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number7'              => ['index' => 49, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number8'              => ['index' => 50, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number9'              => ['index' => 51, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number10'             => ['index' => 52, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'base_plus_delete_flag'         => ['index' => 53, 'validate' => 'bail|nullable|boolean|max:1'],
                    'base_plus_created_at'          => ['index' => 56, 'validate' => 'bail|nullable|date'],
                    'base_plus_user_created_by'     => ['index' => 57, 'validate' => 'bail|nullable|string|max:8'],
                    'base_plus_program_created_by'  => ['index' => 58, 'validate' => 'bail|nullable|string|max:12'],
                    'base_plus_updated_at'          => ['index' => 61, 'validate' => 'bail|nullable|date'],
                    'base_plus_user_updated_by'     => ['index' => 62, 'validate' => 'bail|nullable|string|max:8'],
                    'base_plus_program_updated_by'  => ['index' => 63, 'validate' => 'bail|nullable|string|max:12']
                ],
                'set_fix_info' => [
                    'creating_type' => 1,
                    'can_display'   => true,
                    'remark' => ''
                ]
            ],
            'products' => [
                'program_name'     => "商品マスタ自動連携処理",
                'end_file_path'    => "/mnt/scp_sv/master/BS36BF01.end",
                'tsv_file_path'    => "/mnt/scp_sv/master/BS36BF01.txt",
                'zip_file_path'    => "/home/backup/base_plus/",
                'zip_file_name'    => "%s_products.zip",
                'tsv_file_columns' => 68,
                'set_column_index' => [
                    'product_name'                          => ['index' => 1, 'validate' => 'bail|nullable|string|max:40'],
                    'product_code'                          => ['index' => 4, 'validate' => 'bail|nullable|string|max:15'],
                    'result_addup_code'                     => ['index' => 5, 'validate' => 'bail|nullable|string|max:10'],
                    'result_addup_name'                     => ['index' => 6, 'validate' => 'bail|nullable|string|max:30'],
                    'result_addup_abbreviation'             => ['index' => 7, 'validate' => 'bail|nullable|string|max:10'],
                    'product_large_category'                => ['index' => 9, 'validate' => 'bail|nullable|string|max:3'],
                    'product_middle_category'               => ['index' => 10, 'validate' => 'bail|nullable|string|max:3'],
                    'product_class'                         => ['index' => 11, 'validate' => 'bail|nullable|string|max:1|in:1,2'],
                    'custom_product_flag'                   => ['index' => 12, 'validate' => 'bail|nullable|boolean'],
                    'sales_order_unit'                      => ['index' => 13, 'validate' => 'bail|nullable|string|max:3'],
                    'sales_order_unit_quantity'             => ['index' => 14, 'validate' => 'bail|nullable|string|max:10'],
                    'minimum_sales_order_unit_quantity'     => ['index' => 15, 'validate' => 'bail|nullable|string|max:10'],
                    'statement_of_delivery_name'            => ['index' => 16, 'validate' => 'bail|nullable|string|max:50'],
                    'pickup_slip_message'                   => ['index' => 17, 'validate' => 'bail|nullable|string|max:40'],
                    'lot_target_flag'                       => ['index' => 18, 'validate' => 'bail|nullable|boolean'],
                    'species_name'                          => ['index' => 19, 'validate' => 'bail|nullable|string|max:25'],
                    'export_target_flag'                    => ['index' => 20, 'validate' => 'bail|nullable|boolean'],
                    'net_weight'                            => ['index' => 21, 'validate' => 'bail|nullable|numeric|max:999999999.999'],
                    'gross_weight'                          => ['index' => 22, 'validate' => 'bail|nullable|numeric|max:999999999.999'],
                    'depth'                                 => ['index' => 23, 'validate' => 'bail|nullable|numeric|max:9999999.99'],
                    'width'                                 => ['index' => 24, 'validate' => 'bail|nullable|numeric|max:9999999.99'],
                    'height'                                => ['index' => 25, 'validate' => 'bail|nullable|numeric|max:9999999.99'],
                    'country_of_origin'                     => ['index' => 26, 'validate' => 'bail|nullable|string|max:2'],
                    'itm_class2'                            => ['index' => 27, 'validate' => 'bail|nullable|string|max:2'],
                    'itm_class3'                            => ['index' => 28, 'validate' => 'bail|nullable|string|max:2'],
                    'itm_class4'                            => ['index' => 29, 'validate' => 'bail|nullable|string|max:2'],
                    'itm_class5'                            => ['index' => 30, 'validate' => 'bail|nullable|string|max:2'],
                    'itm_flag1'                             => ['index' => 31, 'validate' => 'bail|nullable|boolean'],
                    'itm_flag2'                             => ['index' => 32, 'validate' => 'bail|nullable|boolean'],
                    'itm_flag3'                             => ['index' => 33, 'validate' => 'bail|nullable|boolean'],
                    'itm_flag4'                             => ['index' => 34, 'validate' => 'bail|nullable|boolean'],
                    'itm_flag5'                             => ['index' => 35, 'validate' => 'bail|nullable|boolean'],
                    'reserved_text1'                        => ['index' => 36, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text2'                        => ['index' => 37, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text3'                        => ['index' => 38, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text4'                        => ['index' => 39, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text5'                        => ['index' => 40, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text6'                        => ['index' => 41, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text7'                        => ['index' => 42, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text8'                        => ['index' => 43, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text9'                        => ['index' => 44, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text10'                       => ['index' => 45, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_number1'                      => ['index' => 46, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number2'                      => ['index' => 47, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number3'                      => ['index' => 48, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number4'                      => ['index' => 49, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number5'                      => ['index' => 50, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number6'                      => ['index' => 51, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number7'                      => ['index' => 52, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number8'                      => ['index' => 53, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number9'                      => ['index' => 54, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'reserved_number10'                     => ['index' => 55, 'validate' => 'bail|nullable|numeric|max:999999999999999999.9'],
                    'base_plus_delete_flag'                 => ['index' => 56, 'validate' => 'bail|nullable|boolean'],
                    'base_plus_created_at'                  => ['index' => 59, 'validate' => 'bail|nullable|date'],
                    'base_plus_user_created_by'             => ['index' => 60, 'validate' => 'bail|nullable|string|max:8'],
                    'base_plus_program_created_by'          => ['index' => 61, 'validate' => 'bail|nullable|string|max:12'],
                    'base_plus_updated_at'                  => ['index' => 64, 'validate' => 'bail|nullable|date'],
                    'base_plus_user_updated_by'             => ['index' => 65, 'validate' => 'bail|nullable|string|max:8'],
                    'base_plus_program_updated_by'          => ['index' => 66, 'validate' => 'bail|nullable|string|max:12']
                ],
                'set_fix_info' => [
                    'creating_type' => 1,
                    'remark' => ''
                ]
            ],
            'product_prices' => [
                'program_name'     => "商品価格マスタ自動連携処理",
                'end_file_path'    => "/mnt/scp_sv/master/BS36BF05.end",
                'tsv_file_path'    => "/mnt/scp_sv/master/BS36BF05.txt",
                'zip_file_path'    => "/home/backup/base_plus/",
                'zip_file_name'    => "%s_product_prices.zip",
                'tsv_file_columns' => 46,
                'set_column_index' => [
                    'supplier_code'                 => ['index' => 1, 'validate' => 'bail|required|string|max:8'],
                    'delivery_destination_code'     => ['index' => 2, 'validate' => 'bail|required_if:supplier_price_class,1|string|max:10'],
                    'product_code'                  => ['index' => 6, 'validate' => 'bail|required|string|max:15'],
                    'currency_code'                 => ['index' => 9, 'validate' => 'bail|nullable|string|max:3'],
                    'supplier_price_class'          => ['index' => 10, 'validate' => 'bail|required|numeric|in:1,3'],
                    'application_started_on'        => ['index' => 11, 'validate' => 'bail|required|date|max:8'],
                    'application_ended_on'          => ['index' => 12, 'validate' => 'bail|nullable|date|max:8'],
                    'unit_price'                    => ['index' => 13, 'validate' => 'bail|nullable|numeric|max:99999999999999.99999'],
                    'reserved_text1'                => ['index' => 14, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text2'                => ['index' => 15, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text3'                => ['index' => 16, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text4'                => ['index' => 17, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text5'                => ['index' => 18, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text6'                => ['index' => 19, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text7'                => ['index' => 20, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text8'                => ['index' => 21, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text9'                => ['index' => 22, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text10'               => ['index' => 23, 'validate' => 'bail|nullable|string|max:200'],
                    'reserved_number1'              => ['index' => 24, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number2'              => ['index' => 25, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number3'              => ['index' => 26, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number4'              => ['index' => 27, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number5'              => ['index' => 28, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number6'              => ['index' => 29, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number7'              => ['index' => 30, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number8'              => ['index' => 31, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number9'              => ['index' => 32, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'reserved_number10'             => ['index' => 33, 'validate' => 'bail|nullable|numeric|max:999999999999999999.99999'],
                    'base_plus_delete_flag'         => ['index' => 34, 'validate' => 'bail|nullable|boolean|max:1'],
                    'base_plus_created_at'          => ['index' => 37, 'validate' => 'bail|nullable|date'],
                    'base_plus_user_created_by'     => ['index' => 38, 'validate' => 'bail|nullable|string|max:8'],
                    'base_plus_program_created_by'  => ['index' => 39, 'validate' => 'bail|nullable|string|max:12'],
                    'base_plus_updated_at'          => ['index' => 42, 'validate' => 'bail|nullable|date'],
                    'base_plus_user_updated_by'     => ['index' => 43, 'validate' => 'bail|nullable|string|max:8'],
                    'base_plus_program_updated_by'  => ['index' => 44, 'validate' => 'bail|nullable|string|max:12']
                ],
                'supplier_price_class_list' => [
                    'product_special_prices' => '1',
                    'product_prices' => '3',
                ],
                'unset_list' => [
                    'product_special_prices' => [
                        'supplier_code',
                        'supplier_price_class'
                    ],
                    'product_prices' => [
                        'supplier_code',
                        'delivery_destination_code',
                        'supplier_price_class',
                        'application_ended_on'
                    ]
                ]
            ]
        ],
        'order' => [
            'orderings' => [
                'program_name'           => 'VVF基幹発注データ取込処理',
                'end_file_path_rule'     => '/mnt/scp_sv/tran/BS36BF21_*.end',
                'skipped_rows_file_path' => '/mnt/scp_sv/tran/skipped.txt',
                'zip_file_path'          => '/home/backup/base_plus/',
                'zip_file_name'          => '%s_orderings.zip',
                'tsv_file_columns'       => 194,
                'set_column_index'       => [
                    // 発注
                    'process_class'                   => ['index' => 0,  'validate' => 'bail|nullable|string|max:1'],
                    'ordering_own_company_code'       => ['index' => 1,  'validate' => 'bail|nullable|string|max:6'],
                    'place_order_number'              => ['index' => 2,  'validate' => 'bail|required|string|max:10'],
                    'place_order_chapter_number'      => ['index' => 3,  'validate' => 'bail|required|string|max:3'],
                    'small_peace_of_peper_type_class' => ['index' => 4,  'validate' => 'bail|nullable|string|max:1'],
                    'small_peace_of_peper_type_code'  => ['index' => 5,  'validate' => 'bail|nullable|string|max:2'],
                    'supplier_flag'                   => ['index' => 6,  'validate' => 'bail|nullable|string|max:8|exists:factories,supplier_code'],
                    'ordering_tax_class'              => ['index' => 7,  'validate' => 'bail|nullable|string|max:1'],
                    'purchase_staff_code'             => ['index' => 8,  'validate' => 'bail|nullable|string|max:8'],
                    'purchase_staff_name'             => ['index' => 9,  'validate' => 'bail|nullable|string|max:30'],
                    'ordering_currency_code'          => ['index' => 10, 'validate' => 'bail|nullable|string|max:3'],
                    'oversea_pay_terms_class'         => ['index' => 11, 'validate' => 'bail|nullable|string|max:2'],
                    'trade_terms_class'               => ['index' => 12, 'validate' => 'bail|nullable|string|max:2'],
                    'loading_port_code'               => ['index' => 13, 'validate' => 'bail|nullable|string|max:4'],
                    'loading_port_name'               => ['index' => 14, 'validate' => 'bail|nullable|string|max:20'],
                    'trade_means_remark'              => ['index' => 15, 'validate' => 'bail|nullable|string|max:15'],
                    'ordering_maintain_period_flag'   => ['index' => 16, 'validate' => 'bail|nullable|boolean'],
                    'supplier_staff_name'             => ['index' => 17, 'validate' => 'bail|nullable|string|max:30'],
                    'place_order_work_staff_code'     => ['index' => 18, 'validate' => 'bail|nullable|string|max:8'],
                    'place_order_work_staff_name'     => ['index' => 19, 'validate' => 'bail|nullable|string|max:30'],
                    'ordering_compleat_flag'          => ['index' => 20, 'validate' => 'bail|nullable|boolean'],
                    'ordering_base_plus_delete_flag'  => ['index' => 21, 'validate' => 'bail|nullable|boolean'],
                    // 発注詳細
                    'place_order_annulment_reason_code'             => ['index' => 22,  'validate' => 'bail|nullable|string|max:2'],
                    'edl_send_compleate_flag'                       => ['index' => 23,  'validate' => 'bail|nullable|boolean'],
                    'edl_information_class'                         => ['index' => 24,  'validate' => 'bail|nullable|string|max:4'],
                    'place_order_date'                              => ['index' => 25,  'validate' => 'bail|nullable|string|max:8'],
                    'order_contract_receive_date'                   => ['index' => 26,  'validate' => 'bail|nullable|string|max:8'],
                    'order_class'                                   => ['index' => 27,  'validate' => 'bail|nullable|string|max:1'],
                    'product_class'                                 => ['index' => 28,  'validate' => 'bail|nullable|string|max:1'],
                    'supplier_product_name'                         => ['index' => 29,  'validate' => 'bail|nullable|string|max:50'],
                    'ordering_details_customer_product_name'        => ['index' => 30,  'validate' => 'bail|nullable|string|max:50'],
                    'ordering_details_product_name'                 => ['index' => 31,  'validate' => 'bail|nullable|string|max:40'],
                    'ordering_details_special_spec_code'            => ['index' => 32,  'validate' => 'bail|nullable|string|max:10'],
                    'ordering_details_product_number'               => ['index' => 33,  'validate' => 'bail|nullable|string|max:15|exists:products,product_code'],
                    'ordering_details_maker_code'                   => ['index' => 34,  'validate' => 'bail|nullable|string|max:8'],
                    'request_delivery_date'                         => ['index' => 35,  'validate' => 'bail|nullable|string|max:8'],
                    'answer_delivery_date'                          => ['index' => 36,  'validate' => 'bail|nullable|string|max:8'],
                    'ordering_details_requestor_organization_code'  => ['index' => 37,  'validate' => 'bail|nullable|string|max:6'],
                    'ordering_details_organization_name'            => ['index' => 38,  'validate' => 'bail|nullable|string|max:40'],
                    'ordering_details_customer_code'                => ['index' => 39,  'validate' => 'bail|nullable|string|max:8|exists:end_users,end_user_code'],
                    'customer_place_order_last_code'                => ['index' => 40,  'validate' => 'bail|nullable|string|max:8'],
                    'base_plue_end_user_code'                       => ['index' => 41,  'validate' => 'bail|nullable|string|max:10'],
                    'supplier_place_order_quantity'                 => ['index' => 42,  'validate' => 'bail|nullable|numeric'],
                    'supplier_purchase_compleate_quantity'          => ['index' => 43,  'validate' => 'bail|nullable|numeric'],
                    'supplier_closed_quantity'                      => ['index' => 44,  'validate' => 'bail|nullable|numeric'],
                    'place_order_quantity'                          => ['index' => 45,  'validate' => 'bail|nullable|numeric'],
                    'arrival_plan_quantity'                         => ['index' => 46,  'validate' => 'bail|nullable|numeric'],
                    'arrival_compleate_quantity'                    => ['index' => 47,  'validate' => 'bail|nullable|numeric'],
                    'stock_compleate_quantity'                      => ['index' => 48,  'validate' => 'bail|nullable|numeric'],
                    'purchase_compleate_quantity'                   => ['index' => 49,  'validate' => 'bail|nullable|numeric'],
                    'cancellation_quantity'                         => ['index' => 50,  'validate' => 'bail|nullable|numeric'],
                    'cancellation_delivery_compleate_quantity'      => ['index' => 51,  'validate' => 'bail|nullable|numeric'],
                    'place_order_unit_code'                         => ['index' => 52,  'validate' => 'bail|nullable|string|max:3'],
                    'supplier_place_order_unit'                     => ['index' => 53,  'validate' => 'bail|nullable|numeric'],
                    'place_order_amount'                            => ['index' => 54,  'validate' => 'bail|nullable|numeric'],
                    'place_order_unit'                              => ['index' => 55,  'validate' => 'bail|nullable|numeric'],
                    'contract_flag'                                 => ['index' => 56,  'validate' => 'bail|nullable|boolean'],
                    'place_order_message'                           => ['index' => 57,  'validate' => 'bail|nullable|string|max:50'],
                    'supplier_instructions'                         => ['index' => 58,  'validate' => 'bail|nullable|string|max:50'],
                    'ordering_details_buyer_remark'                 => ['index' => 59,  'validate' => 'bail|nullable|string|max:50'],
                    'ordering_details_delivery_destination_code'    => ['index' => 60,  'validate' => 'bail|nullable|string|max:10|exists:delivery_destinations,delivery_destination_code'],
                    'warehouse_code'                                => ['index' => 61,  'validate' => 'bail|nullable|string|max:10'],
                    'orders_sheet_issue_flag'                       => ['index' => 62,  'validate' => 'bail|nullable|boolean'],
                    'orders_sheet_issue_date'                       => ['index' => 63,  'validate' => 'bail|nullable|string|max:8'],
                    'construction_develop_number'                   => ['index' => 64,  'validate' => 'bail|nullable|string|max:10'],
                    'estimation_approval_number'                    => ['index' => 65,  'validate' => 'bail|nullable|string|max:15'],
                    'supplier_recived_order_number'                 => ['index' => 66,  'validate' => 'bail|nullable|string|max:14'],
                    'supplier_original_recived_order_pickup_number' => ['index' => 67,  'validate' => 'bail|nullable|string|max:14'],
                    'manufacturing_class'                           => ['index' => 68,  'validate' => 'bail|nullable|string|max:2'],
                    'ordering_details_inspection_spec_sentence'     => ['index' => 69,  'validate' => 'bail|nullable|string|max:20'],
                    'inspection_circulation'                        => ['index' => 70,  'validate' => 'bail|nullable|numeric'],
                    'statement_delivery_date'                       => ['index' => 71,  'validate' => 'bail|nullable|string|max:8'],
                    'set_product_name'                              => ['index' => 72,  'validate' => 'bail|nullable|string|max:40'],
                    'set_maker'                                     => ['index' => 73,  'validate' => 'bail|nullable|string|max:8'],
                    'set_special_spec_code'                         => ['index' => 74,  'validate' => 'bail|nullable|string|max:10'],
                    'ordering_details_repair_order_flag'            => ['index' => 75,  'validate' => 'bail|nullable|boolean'],
                    'ordering_details_goods_name'                   => ['index' => 76,  'validate' => 'bail|nullable|string|max:40'],
                    'ordering_details_goods_quantity'               => ['index' => 77,  'validate' => 'bail|nullable|numeric'],
                    'compleate_flag'                                => ['index' => 78,  'validate' => 'bail|nullable|boolean'],
                    'unofficial_recived_order_flag'                 => ['index' => 79,  'validate' => 'bail|nullable|boolean'],
                    'base_plus_delete_flag'                         => ['index' => 80,  'validate' => 'bail|nullable|boolean'],
                    'reserved_text1'                                => ['index' => 81,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text2'                                => ['index' => 82,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text3'                                => ['index' => 83,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text4'                                => ['index' => 84,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text5'                                => ['index' => 85,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text6'                                => ['index' => 86,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text7'                                => ['index' => 87,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text8'                                => ['index' => 88,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text9'                                => ['index' => 89,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_text10'                               => ['index' => 90,  'validate' => 'bail|nullable|string|max:200'],
                    'reserved_number1'                              => ['index' => 91,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number2'                              => ['index' => 92,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number3'                              => ['index' => 93,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number4'                              => ['index' => 94,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number5'                              => ['index' => 95,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number6'                              => ['index' => 96,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number7'                              => ['index' => 97,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number8'                              => ['index' => 98,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number9'                              => ['index' => 99,  'validate' => 'bail|nullable|numeric'],
                    'reserved_number10'                             => ['index' => 100, 'validate' => 'bail|nullable|numeric'],
                    'ordering_details_base_plus_created_at'         => ['index' => 101, 'validate' => 'bail|nullable|date'],
                    'ordering_details_base_plus_user_created_by'    => ['index' => 104, 'validate' => 'bail|nullable|string|max:8'],
                    'ordering_details_base_plus_program_created_by' => ['index' => 105, 'validate' => 'bail|nullable|string|max:12'],
                    'ordering_details_base_plus_updated_at'         => ['index' => 106, 'validate' => 'bail|nullable|date'],
                    'ordering_details_base_plus_user_updated_by'    => ['index' => 109, 'validate' => 'bail|nullable|string|max:8'],
                    'ordering_details_base_plus_program_updated_by' => ['index' => 110, 'validate' => 'bail|nullable|string|max:12'],
                    // 受注
                    'received_orders_own_company_code'          => ['index' => 112, 'validate' => 'bail|nullable|string|max:6'],
                    'recived_order_number'                      => ['index' => 113, 'validate' => 'bail|nullable|string|max:10'],
                    'recived_order_chapter_number'              => ['index' => 114, 'validate' => 'bail|nullable|string|max:3'],
                    'customer_order_number'                     => ['index' => 115, 'validate' => 'bail|nullable|string|max:23'],
                    'end_user_order_number'                     => ['index' => 116, 'validate' => 'bail|nullable|string|max:17'],
                    'pickup_type_class'                         => ['index' => 117, 'validate' => 'bail|nullable|string|max:1'],
                    'pickup_type_code'                          => ['index' => 118, 'validate' => 'bail|nullable|string|max:2'],
                    'lc_trade_flag'                             => ['index' => 119, 'validate' => 'bail|nullable|boolean'],
                    'lc_number'                                 => ['index' => 120, 'validate' => 'bail|nullable|string|max:30'],
                    'basis_for_recording_sales_class'           => ['index' => 121, 'validate' => 'bail|nullable|string|max:1'],
                    'received_orders_customer_code'             => ['index' => 122, 'validate' => 'bail|nullable|string|max:8'],
                    'received_orders_delivery_destination_code' => ['index' => 123, 'validate' => 'bail|nullable|string|max:10'],
                    'lease_flag'                                => ['index' => 124, 'validate' => 'bail|nullable|boolean'],
                    'destination_code'                          => ['index' => 125, 'validate' => 'bail|nullable|string|max:8'],
                    'statement_delivery_price_display_class'    => ['index' => 126, 'validate' => 'bail|nullable|string|max:1'],
                    'statement_delivery_class'                  => ['index' => 127, 'validate' => 'bail|nullable|string|max:1'],
                    'invoice_issue_flag'                        => ['index' => 128, 'validate' => 'bail|nullable|boolean'],
                    'oversea_flag'                              => ['index' => 129, 'validate' => 'bail|nullable|boolean'],
                    'seller_code'                               => ['index' => 130, 'validate' => 'bail|nullable|string|max:8'],
                    'seller_name'                               => ['index' => 131, 'validate' => 'bail|nullable|string|max:30'],
                    'customer_staff_name'                       => ['index' => 132, 'validate' => 'bail|nullable|string|max:30'],
                    'suite_name'                                => ['index' => 133, 'validate' => 'bail|nullable|string|max:30'],
                    'suite_class'                               => ['index' => 134, 'validate' => 'bail|nullable|string|max:1'],
                    'suite_statement_delivery_remark'           => ['index' => 135, 'validate' => 'bail|nullable|string|max:100'],
                    'received_orders_tax_class'                 => ['index' => 136, 'validate' => 'bail|nullable|string|max:1'],
                    'received_orders_currency_code'             => ['index' => 137, 'validate' => 'bail|nullable|string|max:3'],
                    'payment_installments_flag'                 => ['index' => 138, 'validate' => 'bail|nullable|boolean'],
                    'delivery_compleate_flag'                   => ['index' => 139, 'validate' => 'bail|nullable|boolean'],
                    'shipment_stop_flag'                        => ['index' => 140, 'validate' => 'bail|nullable|boolean'],
                    'free_reason_code'                          => ['index' => 141, 'validate' => 'bail|nullable|string|max:2'],
                    'received_orders_maintain_period_flag'      => ['index' => 142, 'validate' => 'bail|nullable|boolean'],
                    'recived_order_date'                        => ['index' => 143, 'validate' => 'bail|nullable|string|max:8'],
                    'received_orders_compleat_flag'             => ['index' => 144, 'validate' => 'bail|nullable|boolean'],
                    'destinations_segment'                      => ['index' => 145, 'validate' => 'bail|nullable|string|max:10'],
                    'end_user_code'                             => ['index' => 146, 'validate' => 'bail|nullable|string|max:8'],
                    'received_orders_base_plus_delete_flag'     => ['index' => 147, 'validate' => 'bail|nullable|boolean'],
                    // 受注詳細
                    'recived_order_annulment_reason_code'                 => ['index' => 148, 'validate' => 'bail|nullable|string|max:2'],
                    'prodcut_class'                                       => ['index' => 149, 'validate' => 'bail|nullable|string|max:1'],
                    'received_order_details_customer_product_name'        => ['index' => 150, 'validate' => 'bail|nullable|string|max:50'],
                    'received_order_details_product_name'                 => ['index' => 151, 'validate' => 'bail|nullable|string|max:40'],
                    'received_order_details_special_spec_code'            => ['index' => 152, 'validate' => 'bail|nullable|string|max:10'],
                    'received_order_details_maker_code'                   => ['index' => 153, 'validate' => 'bail|nullable|string|max:8'],
                    'received_order_details_product_number'               => ['index' => 154, 'validate' => 'bail|nullable|string|max:15'],
                    'received_order_details_requestor_organization_code'  => ['index' => 155, 'validate' => 'bail|nullable|string|max:6'],
                    'received_order_details_organization_name'            => ['index' => 156, 'validate' => 'bail|nullable|string|max:40'],
                    'received_order_details_inspection_spec_sentence'     => ['index' => 157, 'validate' => 'bail|nullable|string|max:220'],
                    'attached_item'                                       => ['index' => 158, 'validate' => 'bail|nullable|string|max:220'],
                    'detail_payment_installments_flag'                    => ['index' => 159, 'validate' => 'bail|nullable|boolean'],
                    'customer_recived_order_quantity'                     => ['index' => 160, 'validate' => 'bail|nullable|numeric'],
                    'customer_sales_compleate_quantity'                   => ['index' => 161, 'validate' => 'bail|nullable|numeric'],
                    'customer_closed_quantity'                            => ['index' => 162, 'validate' => 'bail|nullable|numeric'],
                    'recived_order_quantity'                              => ['index' => 163, 'validate' => 'bail|nullable|numeric'],
                    'recived_order_shipment_compleate_quantity'           => ['index' => 164, 'validate' => 'bail|nullable|numeric'],
                    'recived_order_sales_compleate_quantity'              => ['index' => 165, 'validate' => 'bail|nullable|numeric'],
                    'recived_order_unit'                                  => ['index' => 166, 'validate' => 'bail|nullable|string|max:3'],
                    'stock_unit'                                          => ['index' => 167, 'validate' => 'bail|nullable|string|max:3'],
                    'customer_recived_order_unit'                         => ['index' => 168, 'validate' => 'bail|nullable|numeric'],
                    'recived_order_unit_amount'                           => ['index' => 169, 'validate' => 'bail|nullable|numeric'],
                    'customer_recived_order_total'                        => ['index' => 170, 'validate' => 'bail|nullable|numeric'],
                    'invoice_display_unit'                                => ['index' => 171, 'validate' => 'bail|nullable|numeric'],
                    'invoice_display_total'                               => ['index' => 172, 'validate' => 'bail|nullable|numeric'],
                    'saller_instructions'                                 => ['index' => 173, 'validate' => 'bail|nullable|string|max:50'],
                    'recived_order_person_remark'                         => ['index' => 174, 'validate' => 'bail|nullable|string|max:50'],
                    'received_order_details_buyer_remark'                 => ['index' => 175, 'validate' => 'bail|nullable|string|max:50'],
                    'buyer_barcode_information'                           => ['index' => 176, 'validate' => 'bail|nullable|string|max:23'],
                    'research_development_product_number'                 => ['index' => 177, 'validate' => 'bail|nullable|string|max:10'],
                    'received_order_details_repair_order_flag'            => ['index' => 178, 'validate' => 'bail|nullable|boolean'],
                    'received_order_details_goods_name'                   => ['index' => 179, 'validate' => 'bail|nullable|string|max:40'],
                    'received_order_details_goods_quantity'               => ['index' => 180, 'validate' => 'bail|nullable|numeric'],
                    'compleat_flag'                                       => ['index' => 181, 'validate' => 'bail|nullable|boolean'],
                    'received_order_details_base_plus_delete_flag'        => ['index' => 182, 'validate' => 'bail|nullable|boolean'],
                    'received_order_details_base_plus_created_at'         => ['index' => 183, 'validate' => 'bail|nullable|date'],
                    'received_order_details_base_plus_user_created_by'    => ['index' => 186, 'validate' => 'bail|nullable|string|max:8'],
                    'received_order_details_base_plus_program_created_by' => ['index' => 187, 'validate' => 'bail|nullable|string|max:12'],
                    'received_order_details_base_plus_updated_at'         => ['index' => 188, 'validate' => 'bail|nullable|date'],
                    'received_order_details_base_plus_user_updated_by'    => ['index' => 191, 'validate' => 'bail|nullable|string|max:8'],
                    'received_order_details_base_plus_program_updated_by' => ['index' => 192, 'validate' => 'bail|nullable|string|max:12']
                ]
            ]
        ],
        'plan' => [
            'growth_simulation' => [
                'max_pattern' => 5
            ],
            'planned_cultivation_status_work' => [
                'file_name' => '生産計画帳票',
                'floor_cultivation_stock' => [
                    'sheet_title' => '各階栽培株数一覧表',
                    'base_column' => 3,
                    'base_row'    => 5
                ],
                'floor_cultivation_stock_sum' => [
                    'sheet_title' => '各階栽培株数合計表',
                    'base_column' => 3,
                    'base_row'    => 5
                ],
                'cultivation_simulation' => [
                    'sheet_title' => '栽培シュミレーション',
                    'base_column' => 4,
                    'base_row'    => 5
                ],
            ],
            'growth_sale_management' => [
                'sheet_lock_pass' => 'Qd9rSLHM',
                'visible_sheet' => [
                    'sheet_title'                                      => '生産・販売管理表',
                    'pack_number_set_num'                              => 11,
                    'before_delivery_factory_product_datas_output_row' => 9,
                    'not_delivery_destination_column_num'              => 7,
                    'fixed_row_number' => [
                        'header_row'                    => '1',
                        'title_row'                     => '2',
                        'product_weight_row'            => '3',
                        'product_header_first_row'      => '4',
                        'product_header_second_row'     => '5',
                        'product_multi_data_row'        => '6',
                        'delivery_destination_name_row' => '7',
                        'assist_space_row'              => '8',
                        'end_row'                       => '68'
                    ],
                    'target_sum_week_cell_list' => [
                        23 => 'E69',
                        38 => 'E23',
                        53 => 'E38',
                        68 => 'E53'
                    ],
                    'skip_row_cnt' => 7,
                    'column_format_list' => [
                        'integer'                    => '#,##0',
                        'percentage'                 => '0.00%',
                        'number_of_heads'            => '#,##0.0 "株"',
                        'weight_per_number_of_heads' => '#,##0 "g"'
                    ],
                    'product_regulation_background_color' => [
                        'odd'  => '#DAEEF3',
                        'even' => '#EBF1DE'
                    ],
                    'sum_week_background_color'         => '#95B3D7',
                    'not_protect_cell_background_color' => '#FFFF99',
                    'merge_cell_list' => [
                        'A2:J2',
                        'A8:J8',
                        'A3:B7',
                        'C3:C7',
                        'D3:D7',
                        'E3:E7',
                        'F3:F7',
                        'G3:G7',
                        'H3:H7',
                        'I3:J7',
                    ],
                    'merge_cell_pattern_defalut' => [
                        'A',
                        'B',
                        'C',
                        'D',
                        'E',
                        'F',
                        'G',
                        'H',
                        'I',
                        'J'
                    ],
                    'number_set3' => [
                        '4',
                        '5',
                        '6',
                    ],
                    'before_delivery_destination_sub_value' => [
                        '4' => '出来高',
                        '5' => '基本入り株数',
                        '6' => ''
                    ],
                    'in_delivery_destination_sub_value' => [
                        '4' => '販売数量',
                        '5' => 'ケース入数(パック数)',
                        '6' => ''
                    ],
                    'after_delivery_destination_sub_value' => [
                        '4' => '在庫',
                        '5' => 'ケース入数',
                        '6' => ''
                    ],
                    'before_delivery_destination_value' => [
                        '0' => 'パック数',
                        '1' => '使用株数',
                    ],
                    'after_delivery_destination_value' => [
                        '4' => '小計',
                        '3' => '重量(kg)',
                        '2' => '過不足数',
                        '1' => '廃棄',
                        '0' => '在庫数',
                    ],
                    'sum_value' => [
                        '0' => '合計使用株数',
                        '1' => '合計重量(kg)',
                        '2' => '差引過不足株数',
                        '3' => '累積過不足株数',
                        '4' => '',
                        '5' => '①調整（収穫廃棄）',
                        '6' => '②調整（その他）'
                    ],
                    'merge_cell_pattern_1' => [
                        'first_set' => [
                            'A',
                            'B',
                            'C',
                            'D',
                            'E',
                            'F',
                            'G',
                            'H'
                        ],
                        'second_set' => [
                            'I',
                            'J',
                        ],
                        'number_set1' => [
                            'subtotal'           => '1',
                            'weight'             => '2',
                            'over_and_under_num' => '3',
                            'disposal_num'       => '4',
                            'stock_num'          => '5'
                        ],
                        'number_set3' => [
                            'total_use_shares'                 => '6',
                            'total_weight'                     => '7',
                            'deduction_over_and_under_shares'  => '8',
                            'cumulative_over_and_under_shares' => '9',
                            'crop_failure'                     => '11',
                            'advanced_harvest'                 => '12'
                        ],
                        'sum_week_point' => [
                            'start_row' => '9',
                            'end_row'   => '22',
                        ]
                    ],
                    'start_row_crop' => 8,
                    'end_row_crop'   => 66,
                ],
                'hidden_sheet' => [
                    'sheet_title1' => '取込用隠し予想製品化率表',
                    'sheet_title2' => '取込用隠し出来高表',
                ],
                'import_growth_sale' => [
                    'factory_code_cell' => 'B2',
                    'species_code_cell' => 'D2',
                    'remove_fix_row_range' => [
                        'start_row' => 1,
                        'end_row'   => 3,
                    ],
                    'import_key_list' => [
                        'date',
                        'current_product_rate',
                        'product_rate',
                        'current_crop_failure',
                        'crop_failure',
                        'current_advanced_harvest',
                        'advanced_harvest',
                        'updated_at'
                    ],
                    'import_key_list_crop' => [
                        'date',
                        'number_of_heads',
                        'weight_per_number_of_heads',
                        'input_group',
                        'current_crop_number',
                        'crop_number',
                        'updated_at'
                    ],
                    'exclusion_product_rate_message' =>
                        '工場 : %s'.
                        ' / 品種 : %s'.
                        ' / 収穫日 : %s'.
                        ' の予想製品化率データは、ほかの担当者が更新したため取込対象から除外しました。'
                    ,
                    'exclusion_crop_message' =>
                        '工場 : %s'.
                        ' / 品種 : %s'.
                        ' / 基本入り株数 : %s'.
                        ' / 基本入り数あたり重量 : %s'.
                        ' / 出来高入力グループ : %s'.
                        ' / 収穫日 : %s'.
                        ' の出来高データは、ほかの担当者が更新したため取込対象から除外しました。'
                ]
            ]
        ],
        'shipment' => [
            'shipping_data_export' => [
                'program_name'  => '出荷データ送信',
                'end_file_path' => '/mnt/scp_sv/tran/SB36FB21.end',
                'tsv_file_path' => '/mnt/scp_sv/tran/SB36FB21.txt',
                'zip_file_path' => '/home/backup/base_plus/',
                'zip_file_name' => '%s_shipping_data_export.zip'
            ],
        ]
    ],
    'order' => [
        'order_forecasts' => [
            'sheet_lock_pass'      => 'Qd9rSLHM',
            'default_column_width' => 11,
            'default_row_height'   => 19,
            'visible_forecast'     => [
                'forecast_file_name' => 'フォーキャスト表',
                'sheet_name_number'  => 'フォーキャスト表_個数',
                'sheet_name_weight'  => 'フォーキャスト表_重量',
                'header_table_range' => 'B3:BJ10',
                'body_table_range'   => 'B12:BJ%d',
                'freeze_cell'        => 'F13',
                'merge_start_row'    => 15,
                'date_start_column'  => 7,
                'width_set_list'     => [
                    'A' => 2,
                    'B' => 19,
                    'C' => 27,
                    'D' => 10
                ],
                'height_set_list' => [
                    11 => 8,
                    14 => 4
                ]
            ],
            'hidden_forecast' => [
                'sheet_name' => '隠し取込用フォーキャスト表',
            ],
            'import_forecast' => [
                'factory_code_cell'    => 'B2',
                'remove_fix_row_range' => [
                    'start_row' => 1,
                    'end_row'   => 3,
                ],
                'import_key_list' => [
                    'date',
                    'factory_product_sequence_number',
                    'delivery_destination_code',
                    'current_forecast_number',
                    'forecast_number',
                    'updated_at',
                    'can_import'
                ],
                'exclusion_message' =>
                    '納入先 : %s'.
                    ' / 工場取扱商品 : %s'.
                    ' / 納期 : %s'.
                    ' のデータは、ほかの担当者が更新したため取込対象から除外しました。'
            ]
        ],
        'whiteboard_reference' => [
            'reload_interval' => 300, // ホワイトボード情報参照画面自動更新間隔(秒)
        ]
    ]
];
