<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Cake\Chronos\Chronos;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->delete();

        DB::table('menus')->insert([
            /** 生産計画 **/
            [
                'category'        => 'growth_simulation',
                'tab_no'          => 1,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '生産計画',
                'tab_code'        => 'plan',
                'group_name'      => '生産シミュレーション',
                'category_name'   => 'シミュレーション一覧',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'growth_simulation_fixed',
                'tab_no'          => 1,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => '生産計画',
                'tab_code'        => 'plan',
                'group_name'      => '生産シミュレーション',
                'category_name'   => 'シミュレーション確定一覧',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'bed_states',
                'tab_no'          => 1,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 3,
                'tab_name'        => '生産計画',
                'tab_code'        => 'plan',
                'group_name'      => '生産シミュレーション',
                'category_name'   => 'ベッド状況確認',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'growth_sale_management_summary',
                'tab_no'          => 1,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '生産計画',
                'tab_code'        => 'plan',
                'group_name'      => '生産販売管理表',
                'category_name'   => 'サマリー',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'growth_sale_management',
                'tab_no'          => 1,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => '生産計画',
                'tab_code'        => 'plan',
                'group_name'      => '生産販売管理表',
                'category_name'   => 'Excel出力・取込',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'growth_planned_table',
                'tab_no'          => 1,
                'group_column_no' => 3,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '生産計画',
                'tab_code'        => 'plan',
                'group_name'      => '生産計画管理表',
                'category_name'   => 'Excel出力',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'facility_status_list',
                'tab_no'          => 1,
                'group_column_no' => 3,
                'group_row_no'    => 2,
                'category_order'  => 1,
                'tab_name'        => '生産計画',
                'tab_code'        => 'plan',
                'group_name'      => '施設利用状況',
                'category_name'   => 'Excel出力',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            /** 受注 **/
            [
                'category'        => 'order_forecasts',
                'tab_no'          => 2,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '受注',
                'tab_code'        => 'order',
                'group_name'      => 'フォーキャスト',
                'category_name'   => 'フォーキャストExcel取込',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'order_list',
                'tab_no'          => 2,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '受注',
                'tab_code'        => 'order',
                'group_name'      => '参照',
                'category_name'   => '注文一覧',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'whiteboard_reference',
                'tab_no'          => 2,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => '受注',
                'tab_code'        => 'order',
                'group_name'      => '参照',
                'category_name'   => 'ホワイトボード参照',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'order_input',
                'tab_no'          => 2,
                'group_column_no' => 3,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '受注',
                'tab_code'        => 'order',
                'group_name'      => '入力',
                'category_name'   => '注文入力',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'purchase_order_excel_import',
                'tab_no'          => 2,
                'group_column_no' => 3,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => '受注',
                'tab_code'        => 'order',
                'group_name'      => '入力',
                'category_name'   => 'Excel取込',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'returned_products',
                'tab_no'          => 2,
                'group_column_no' => 3,
                'group_row_no'    => 1,
                'category_order'  => 3,
                'tab_name'        => '受注',
                'tab_code'        => 'order',
                'group_name'      => '入力',
                'category_name'   => '返品入力',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            /** 工場生産活動 **/
            [
                'category'        => 'work_instruction',
                'tab_no'          => 3,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '工場生産活動',
                'tab_code'        => 'factory_production_work',
                'group_name'      => '出力',
                'category_name'   => '作業指示書',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'activity_results',
                'tab_no'          => 3,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '工場生産活動',
                'tab_code'        => 'factory_production_work',
                'group_name'      => '実績入力',
                'category_name'   => '活動実績',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'productized_results',
                'tab_no'          => 4,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '出荷',
                'tab_code'        => 'shipment',
                'group_name'      => '製品引当',
                'category_name'   => '製品化実績',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'form_output',
                'tab_no'          => 4,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '出荷',
                'tab_code'        => 'shipment',
                'group_name'      => '出荷帳票',
                'category_name'   => '出荷作業帳票出力',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'collection_request',
                'tab_no'          => 4,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => '出荷',
                'tab_code'        => 'shipment',
                'group_name'      => '出荷帳票',
                'category_name'   => '集荷依頼書',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'invoices.export',
                'tab_no'          => 4,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 3,
                'tab_name'        => '出荷',
                'tab_code'        => 'shipment',
                'group_name'      => '出荷帳票',
                'category_name'   => '請求書',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'invoices',
                'tab_no'          => 4,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 4,
                'tab_name'        => '出荷',
                'tab_code'        => 'shipment',
                'group_name'      => '出荷帳票',
                'category_name'   => '請求書締め',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'shipment_fix',
                'tab_no'          => 4,
                'group_column_no' => 3,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '出荷',
                'tab_code'        => 'shipment',
                'group_name'      => '確定',
                'category_name'   => '出荷確定',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'shipment_data_export',
                'tab_no'          => 4,
                'group_column_no' => 3,
                'group_row_no'    => 2,
                'category_order'  => 1,
                'tab_name'        => '出荷',
                'tab_code'        => 'shipment',
                'group_name'      => '出力',
                'category_name'   => '出荷データ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            // 在庫管理
            [
                'category'        => 'stocks.summary',
                'tab_no'          => 5,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '在庫',
                'tab_code'        => 'stock',
                'group_name'      => '在庫管理',
                'category_name'   => '在庫サマリー',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'stocks',
                'tab_no'          => 5,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => '在庫',
                'tab_code'        => 'stock',
                'group_name'      => '在庫管理',
                'category_name'   => '在庫一覧',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'stocks.dispose',
                'tab_no'          => 5,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 3,
                'tab_name'        => '在庫',
                'tab_code'        => 'stock',
                'group_name'      => '在庫管理',
                'category_name'   => '廃棄登録',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'stocktaking',
                'tab_no'          => 5,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 4,
                'tab_name'        => '在庫',
                'tab_code'        => 'stock',
                'group_name'      => '在庫管理',
                'category_name'   => '在庫棚卸',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'stock_states',
                'tab_no'          => 5,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => '在庫',
                'tab_code'        => 'stock',
                'group_name'      => '在庫帳票',
                'category_name'   => '在庫状況確認',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'stock_histories',
                'tab_no'          => 5,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => '在庫',
                'tab_code'        => 'stock',
                'group_name'      => '在庫帳票',
                'category_name'   => '在庫履歴一覧',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            // マスタ管理
            [
                'category'        => 'products',
                'tab_no'          => 6,
                'group_column_no' => 1,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '品名',
                'category_name'   => '商品マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'species',
                'tab_no'          => 6,
                'group_column_no' => 1,
                'group_row_no'    => 2,
                'category_order'  => 1,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '品種',
                'category_name'   => '品種マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'corporations',
                'tab_no'          => 6,
                'group_column_no' => 1,
                'group_row_no'    => 3,
                'category_order'  => 1,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '工場',
                'category_name'   => '法人マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'factories',
                'tab_no'          => 6,
                'group_column_no' => 1,
                'group_row_no'    => 3,
                'category_order'  => 1,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '工場',
                'category_name'   => '工場マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'customers',
                'tab_no'          => 6,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '出荷',
                'category_name'   => '得意先マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'end_users',
                'tab_no'          => 6,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 2,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '出荷',
                'category_name'   => 'エンドユーザマスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'delivery_destinations',
                'tab_no'          => 6,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 3,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '出荷',
                'category_name'   => '納入先マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'warehouses',
                'tab_no'          => 6,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 4,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '出荷',
                'category_name'   => '倉庫マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'lead_time',
                'tab_no'          => 6,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 5,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '出荷',
                'category_name'   => 'リードタイム一覧',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'transport_companies',
                'tab_no'          => 6,
                'group_column_no' => 2,
                'group_row_no'    => 1,
                'category_order'  => 6,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => '出荷',
                'category_name'   => '運送会社マスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'users',
                'tab_no'          => 6,
                'group_column_no' => 3,
                'group_row_no'    => 1,
                'category_order'  => 1,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => 'ユーザ',
                'category_name'   => 'ユーザマスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ],
            [
                'category'        => 'calendars',
                'tab_no'          => 6,
                'group_column_no' => 3,
                'group_row_no'    => 2,
                'category_order'  => 1,
                'tab_name'        => 'マスター管理',
                'tab_code'        => 'master',
                'group_name'      => 'その他',
                'category_name'   => 'カレンダーマスタ',
                'created_by'      => 'BATCH',
                'created_at'      => Chronos::now()->format('Y-m-d H:i:s'),
                'updated_by'      => 'BATCH',
                'updated_at'      => Chronos::now()->format('Y-m-d H:i:s')
            ]
        ]);
    }
}
